### ISSUE TITLE
Signs of current use - tiles vs list

### ISSUE THREAD

**Issue by JessGroling** [crsdc/badgerapp#30]
Can we have the 9 badger signs displayed as tiles, rather than as a list?

**Comment by crsdc** [comment]
This turned out to be more complicated than it should have been hence menu for now, but is still planned to be replaced by tiles if possible.

**Comment by crsdc** [comment]
Linked to #35

**Comment by crsdc** [comment]
Image tiles now implemented for the information-only "identify a sett" screen. Checklist screen for "evidence of badger activity at the sett" instead displays a list of horizontal tiles with thumbnail image at left and info icon at right, since two actions are possible here: tick items if they are present, and display more info about each item.

Some changes still to be made to user interface on this screen but the interface we wanted is implemented.
